server:
  port: 6001
spring:
  application:
    name: eureka-consumer-6001

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-8001:8001/eureka/,http://eureka-server-8002:8002/eureka/,http://eureka-server-8003:8003/eureka/
  instance:
    instance-id: eureka-consumer-6001
    ip-address: 127.0.0.1


info:
  app.name: ${spring.application.name}
  port: ${server.port}
  build.artifactId: $project.basedir$
  build.version: $project.version$