server:
  port: 5002

spring:
  application:
    name: eureka-zuul-5002
zuul:
  prefix: /pre  #路由前缀pre/test/zuul/
  routes:
    route1:
      path: /test/zuul/**
      #url: http://localhost:7002  如果不是eureka的服务则使用path
      serviceId: eureka-provider-7001
  ignored-patterns: /test/zuul/a/**
  sensitive-headers: cookies,header #不屏蔽这些
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-8001:8001/eureka/,http://eureka-server-8002:8002/eureka/,http://eureka-server-8003:8003/eureka/
