server:
  port: 7003
spring:
  application:
    name: eureka-provider-7001

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-8001:8001/eureka/,http://eureka-server-8002:8002/eureka/,http://eureka-server-8003:8003/eureka/
    fetch-registry: false  #是否增量从eureka注册中心拉取信息
    register-with-eureka: true   #指示此实例是否应在eureka中注册其信息服务器供他人发现。
  instance:
    instance-id: eureka-provider-7003
    ip-address: 127.0.0.1

info:
  app.name: ${spring.application.name}
  port: ${server.port}
  build.artifactId: $project.basedir$
  build.version: $project.version$