spring:
    profiles:
        active: 
        - dev
           
---
spring:
    profiles: dev
    application: 
        name: dev-application

---
spring:
    profiles: test
    application: 
        name: test-application
