spring:
    profiles:
        active: dev
           
---

spring:
    profiles: dev
    application: 
        name: dev-config-client
server:
    port:4001
---

spring:
    profiles: test
    application: 
        name: test-config-client
server:
    port:4002
