server:
  port: 5004

spring:
  application:
    name: eureka-config-5004
eureka:

  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 90 #非正常下线剔除服务的时间
    ip-address: 127.0.0.1 #只是修改instanceinfo ipAddr
    home-page-url: http://${eureka.instance.hostname}:${server.port}/homepage
    instance-id: eureka-config-5004
    hostname: eureka-config-5004

  client:
    register-with-eureka: false  #不把自己作为客户端注册到eureka
    fetch-registry: false  #从Eureka server获取注册信息并缓存到本地，之后只会增量获取信息
    service-url:
      defaultZone: http://eureka-server-8001:8001/eureka/,http://eureka-server-8002:8002/eureka/,http://eureka-server-8003:8003/eureka/ #serviceUrl指向与本地实例相同的主机。注册中心地址

  server:
    enable-self-preservation: true #自我保护默认开启

cloud:
  config:
    git:
      uri: https://github.com/longnutrasweet/springcloud.git
      search-paths: /config/
      username: longnutrasweet
      password: 19920606aa